<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageId>Katasec.Forge.Mcl.MissionRegistry</PackageId>
    <Version>1.0.0</Version>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForgeMission.Core\ForgeMission.Core.csproj" TreatAsPackageReference="true" Version="[1.0.0]" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Katasec.OciClient" Version="0.2.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="BuiltinMissionReferences/vanilla.oci-ref"
                      LogicalName="ForgeMission.MissionRegistry.BuiltinMissionReferences.vanilla.oci-ref" />
  </ItemGroup>

</Project>
